#%RAML 1.0
---
title: Lapiz HTTP Bridge to Tensorboard
baseUri: http://localhost.com/{version}
version: v1

/status:
  get:
    description: Check server version and health
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "health": "OK",
                  "message": "Tensorboard running at 'http://localhost:6006' in folder '/tmp/tensorboard'",
                  "tensorboard": {
                      "address": "http://localhost:6006",
                      "logdir": "/tmp/tensorboard"
                  },
                  "version": "0.5.0"
              }

/runs:
  description: Collection of available runs
  get:
    description: Retrieve the list of available runs
    responses:
      200:
        body:
          application/json:
            example: |
              [
                'vgg16,lr=1e-3,lambda=1e-1',
                'vgg16,lr=1e-3,lambda=3e-1'
              ]
  /{runName}:
   get:
    description: Details regarding a run
    responses:
      200:
        body:
          application/json:
            example: |
              a json dictionnary with the following entries:
                scalars: the name of all the scalar data entries
                histograms: the name of all the histogram data entries
            description:
              a json dictionnary with the following entries:
                scalars: the name of all the scalar data entries
                histograms: the name of all the histogram data entries
